/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsThemingRouteImport } from './routes/docs/theming'
import { Route as DocsTailwindToKotlinRouteImport } from './routes/docs/tailwind-to-kotlin'
import { Route as DocsIntroductionRouteImport } from './routes/docs/introduction'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as DocsComponentsRouteImport } from './routes/docs/components'
import { Route as DocsComponentsTabsRouteImport } from './routes/docs/components/tabs'
import { Route as DocsComponentsSwitchRouteImport } from './routes/docs/components/switch'
import { Route as DocsComponentsSpinnerRouteImport } from './routes/docs/components/spinner'
import { Route as DocsComponentsSonnerRouteImport } from './routes/docs/components/sonner'
import { Route as DocsComponentsSliderRouteImport } from './routes/docs/components/slider'
import { Route as DocsComponentsSkeletonRouteImport } from './routes/docs/components/skeleton'
import { Route as DocsComponentsSidebarRouteImport } from './routes/docs/components/sidebar'
import { Route as DocsComponentsSelectRouteImport } from './routes/docs/components/select'
import { Route as DocsComponentsRadioGroupRouteImport } from './routes/docs/components/radio-group'
import { Route as DocsComponentsProgressRouteImport } from './routes/docs/components/progress'
import { Route as DocsComponentsPopoverRouteImport } from './routes/docs/components/popover'
import { Route as DocsComponentsInputOtpRouteImport } from './routes/docs/components/input-otp'
import { Route as DocsComponentsInputRouteImport } from './routes/docs/components/input'
import { Route as DocsComponentsDropdownMenuRouteImport } from './routes/docs/components/dropdown-menu'
import { Route as DocsComponentsDrawerRouteImport } from './routes/docs/components/drawer'
import { Route as DocsComponentsDialogRouteImport } from './routes/docs/components/dialog'
import { Route as DocsComponentsDatePickerRouteImport } from './routes/docs/components/date-picker'
import { Route as DocsComponentsDataTableRouteImport } from './routes/docs/components/data-table'
import { Route as DocsComponentsComboboxRouteImport } from './routes/docs/components/combobox'
import { Route as DocsComponentsCollapsibleRouteImport } from './routes/docs/components/collapsible'
import { Route as DocsComponentsCheckboxRouteImport } from './routes/docs/components/checkbox'
import { Route as DocsComponentsChartRouteImport } from './routes/docs/components/chart'
import { Route as DocsComponentsCarouselRouteImport } from './routes/docs/components/carousel'
import { Route as DocsComponentsCardRouteImport } from './routes/docs/components/card'
import { Route as DocsComponentsCalendarRouteImport } from './routes/docs/components/calendar'
import { Route as DocsComponentsButtonRouteImport } from './routes/docs/components/button'
import { Route as DocsComponentsBadgeRouteImport } from './routes/docs/components/badge'
import { Route as DocsComponentsAvatarRouteImport } from './routes/docs/components/avatar'
import { Route as DocsComponentsAlertDialogRouteImport } from './routes/docs/components/alert-dialog'
import { Route as DocsComponentsAlertRouteImport } from './routes/docs/components/alert'
import { Route as DocsComponentsAccordionRouteImport } from './routes/docs/components/accordion'

const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsThemingRoute = DocsThemingRouteImport.update({
  id: '/theming',
  path: '/theming',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsTailwindToKotlinRoute = DocsTailwindToKotlinRouteImport.update({
  id: '/tailwind-to-kotlin',
  path: '/tailwind-to-kotlin',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsIntroductionRoute = DocsIntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsRoute = DocsComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsTabsRoute = DocsComponentsTabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsSwitchRoute = DocsComponentsSwitchRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsSpinnerRoute = DocsComponentsSpinnerRouteImport.update({
  id: '/spinner',
  path: '/spinner',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsSonnerRoute = DocsComponentsSonnerRouteImport.update({
  id: '/sonner',
  path: '/sonner',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsSliderRoute = DocsComponentsSliderRouteImport.update({
  id: '/slider',
  path: '/slider',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsSkeletonRoute = DocsComponentsSkeletonRouteImport.update({
  id: '/skeleton',
  path: '/skeleton',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsSidebarRoute = DocsComponentsSidebarRouteImport.update({
  id: '/sidebar',
  path: '/sidebar',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsSelectRoute = DocsComponentsSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsRadioGroupRoute =
  DocsComponentsRadioGroupRouteImport.update({
    id: '/radio-group',
    path: '/radio-group',
    getParentRoute: () => DocsComponentsRoute,
  } as any)
const DocsComponentsProgressRoute = DocsComponentsProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsPopoverRoute = DocsComponentsPopoverRouteImport.update({
  id: '/popover',
  path: '/popover',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsInputOtpRoute = DocsComponentsInputOtpRouteImport.update({
  id: '/input-otp',
  path: '/input-otp',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsInputRoute = DocsComponentsInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsDropdownMenuRoute =
  DocsComponentsDropdownMenuRouteImport.update({
    id: '/dropdown-menu',
    path: '/dropdown-menu',
    getParentRoute: () => DocsComponentsRoute,
  } as any)
const DocsComponentsDrawerRoute = DocsComponentsDrawerRouteImport.update({
  id: '/drawer',
  path: '/drawer',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsDialogRoute = DocsComponentsDialogRouteImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsDatePickerRoute =
  DocsComponentsDatePickerRouteImport.update({
    id: '/date-picker',
    path: '/date-picker',
    getParentRoute: () => DocsComponentsRoute,
  } as any)
const DocsComponentsDataTableRoute = DocsComponentsDataTableRouteImport.update({
  id: '/data-table',
  path: '/data-table',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsComboboxRoute = DocsComponentsComboboxRouteImport.update({
  id: '/combobox',
  path: '/combobox',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsCollapsibleRoute =
  DocsComponentsCollapsibleRouteImport.update({
    id: '/collapsible',
    path: '/collapsible',
    getParentRoute: () => DocsComponentsRoute,
  } as any)
const DocsComponentsCheckboxRoute = DocsComponentsCheckboxRouteImport.update({
  id: '/checkbox',
  path: '/checkbox',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsChartRoute = DocsComponentsChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsCarouselRoute = DocsComponentsCarouselRouteImport.update({
  id: '/carousel',
  path: '/carousel',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsCardRoute = DocsComponentsCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsCalendarRoute = DocsComponentsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsButtonRoute = DocsComponentsButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsBadgeRoute = DocsComponentsBadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsAvatarRoute = DocsComponentsAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsAlertDialogRoute =
  DocsComponentsAlertDialogRouteImport.update({
    id: '/alert-dialog',
    path: '/alert-dialog',
    getParentRoute: () => DocsComponentsRoute,
  } as any)
const DocsComponentsAlertRoute = DocsComponentsAlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsAccordionRoute = DocsComponentsAccordionRouteImport.update({
  id: '/accordion',
  path: '/accordion',
  getParentRoute: () => DocsComponentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/components': typeof DocsComponentsRouteWithChildren
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/docs/tailwind-to-kotlin': typeof DocsTailwindToKotlinRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/alert': typeof DocsComponentsAlertRoute
  '/docs/components/alert-dialog': typeof DocsComponentsAlertDialogRoute
  '/docs/components/avatar': typeof DocsComponentsAvatarRoute
  '/docs/components/badge': typeof DocsComponentsBadgeRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/calendar': typeof DocsComponentsCalendarRoute
  '/docs/components/card': typeof DocsComponentsCardRoute
  '/docs/components/carousel': typeof DocsComponentsCarouselRoute
  '/docs/components/chart': typeof DocsComponentsChartRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/collapsible': typeof DocsComponentsCollapsibleRoute
  '/docs/components/combobox': typeof DocsComponentsComboboxRoute
  '/docs/components/data-table': typeof DocsComponentsDataTableRoute
  '/docs/components/date-picker': typeof DocsComponentsDatePickerRoute
  '/docs/components/dialog': typeof DocsComponentsDialogRoute
  '/docs/components/drawer': typeof DocsComponentsDrawerRoute
  '/docs/components/dropdown-menu': typeof DocsComponentsDropdownMenuRoute
  '/docs/components/input': typeof DocsComponentsInputRoute
  '/docs/components/input-otp': typeof DocsComponentsInputOtpRoute
  '/docs/components/popover': typeof DocsComponentsPopoverRoute
  '/docs/components/progress': typeof DocsComponentsProgressRoute
  '/docs/components/radio-group': typeof DocsComponentsRadioGroupRoute
  '/docs/components/select': typeof DocsComponentsSelectRoute
  '/docs/components/sidebar': typeof DocsComponentsSidebarRoute
  '/docs/components/skeleton': typeof DocsComponentsSkeletonRoute
  '/docs/components/slider': typeof DocsComponentsSliderRoute
  '/docs/components/sonner': typeof DocsComponentsSonnerRoute
  '/docs/components/spinner': typeof DocsComponentsSpinnerRoute
  '/docs/components/switch': typeof DocsComponentsSwitchRoute
  '/docs/components/tabs': typeof DocsComponentsTabsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/components': typeof DocsComponentsRouteWithChildren
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/docs/tailwind-to-kotlin': typeof DocsTailwindToKotlinRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/alert': typeof DocsComponentsAlertRoute
  '/docs/components/alert-dialog': typeof DocsComponentsAlertDialogRoute
  '/docs/components/avatar': typeof DocsComponentsAvatarRoute
  '/docs/components/badge': typeof DocsComponentsBadgeRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/calendar': typeof DocsComponentsCalendarRoute
  '/docs/components/card': typeof DocsComponentsCardRoute
  '/docs/components/carousel': typeof DocsComponentsCarouselRoute
  '/docs/components/chart': typeof DocsComponentsChartRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/collapsible': typeof DocsComponentsCollapsibleRoute
  '/docs/components/combobox': typeof DocsComponentsComboboxRoute
  '/docs/components/data-table': typeof DocsComponentsDataTableRoute
  '/docs/components/date-picker': typeof DocsComponentsDatePickerRoute
  '/docs/components/dialog': typeof DocsComponentsDialogRoute
  '/docs/components/drawer': typeof DocsComponentsDrawerRoute
  '/docs/components/dropdown-menu': typeof DocsComponentsDropdownMenuRoute
  '/docs/components/input': typeof DocsComponentsInputRoute
  '/docs/components/input-otp': typeof DocsComponentsInputOtpRoute
  '/docs/components/popover': typeof DocsComponentsPopoverRoute
  '/docs/components/progress': typeof DocsComponentsProgressRoute
  '/docs/components/radio-group': typeof DocsComponentsRadioGroupRoute
  '/docs/components/select': typeof DocsComponentsSelectRoute
  '/docs/components/sidebar': typeof DocsComponentsSidebarRoute
  '/docs/components/skeleton': typeof DocsComponentsSkeletonRoute
  '/docs/components/slider': typeof DocsComponentsSliderRoute
  '/docs/components/sonner': typeof DocsComponentsSonnerRoute
  '/docs/components/spinner': typeof DocsComponentsSpinnerRoute
  '/docs/components/switch': typeof DocsComponentsSwitchRoute
  '/docs/components/tabs': typeof DocsComponentsTabsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/components': typeof DocsComponentsRouteWithChildren
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/docs/tailwind-to-kotlin': typeof DocsTailwindToKotlinRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/alert': typeof DocsComponentsAlertRoute
  '/docs/components/alert-dialog': typeof DocsComponentsAlertDialogRoute
  '/docs/components/avatar': typeof DocsComponentsAvatarRoute
  '/docs/components/badge': typeof DocsComponentsBadgeRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/calendar': typeof DocsComponentsCalendarRoute
  '/docs/components/card': typeof DocsComponentsCardRoute
  '/docs/components/carousel': typeof DocsComponentsCarouselRoute
  '/docs/components/chart': typeof DocsComponentsChartRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/collapsible': typeof DocsComponentsCollapsibleRoute
  '/docs/components/combobox': typeof DocsComponentsComboboxRoute
  '/docs/components/data-table': typeof DocsComponentsDataTableRoute
  '/docs/components/date-picker': typeof DocsComponentsDatePickerRoute
  '/docs/components/dialog': typeof DocsComponentsDialogRoute
  '/docs/components/drawer': typeof DocsComponentsDrawerRoute
  '/docs/components/dropdown-menu': typeof DocsComponentsDropdownMenuRoute
  '/docs/components/input': typeof DocsComponentsInputRoute
  '/docs/components/input-otp': typeof DocsComponentsInputOtpRoute
  '/docs/components/popover': typeof DocsComponentsPopoverRoute
  '/docs/components/progress': typeof DocsComponentsProgressRoute
  '/docs/components/radio-group': typeof DocsComponentsRadioGroupRoute
  '/docs/components/select': typeof DocsComponentsSelectRoute
  '/docs/components/sidebar': typeof DocsComponentsSidebarRoute
  '/docs/components/skeleton': typeof DocsComponentsSkeletonRoute
  '/docs/components/slider': typeof DocsComponentsSliderRoute
  '/docs/components/sonner': typeof DocsComponentsSonnerRoute
  '/docs/components/spinner': typeof DocsComponentsSpinnerRoute
  '/docs/components/switch': typeof DocsComponentsSwitchRoute
  '/docs/components/tabs': typeof DocsComponentsTabsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/components'
    | '/docs/installation'
    | '/docs/introduction'
    | '/docs/tailwind-to-kotlin'
    | '/docs/theming'
    | '/docs/components/accordion'
    | '/docs/components/alert'
    | '/docs/components/alert-dialog'
    | '/docs/components/avatar'
    | '/docs/components/badge'
    | '/docs/components/button'
    | '/docs/components/calendar'
    | '/docs/components/card'
    | '/docs/components/carousel'
    | '/docs/components/chart'
    | '/docs/components/checkbox'
    | '/docs/components/collapsible'
    | '/docs/components/combobox'
    | '/docs/components/data-table'
    | '/docs/components/date-picker'
    | '/docs/components/dialog'
    | '/docs/components/drawer'
    | '/docs/components/dropdown-menu'
    | '/docs/components/input'
    | '/docs/components/input-otp'
    | '/docs/components/popover'
    | '/docs/components/progress'
    | '/docs/components/radio-group'
    | '/docs/components/select'
    | '/docs/components/sidebar'
    | '/docs/components/skeleton'
    | '/docs/components/slider'
    | '/docs/components/sonner'
    | '/docs/components/spinner'
    | '/docs/components/switch'
    | '/docs/components/tabs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/components'
    | '/docs/installation'
    | '/docs/introduction'
    | '/docs/tailwind-to-kotlin'
    | '/docs/theming'
    | '/docs/components/accordion'
    | '/docs/components/alert'
    | '/docs/components/alert-dialog'
    | '/docs/components/avatar'
    | '/docs/components/badge'
    | '/docs/components/button'
    | '/docs/components/calendar'
    | '/docs/components/card'
    | '/docs/components/carousel'
    | '/docs/components/chart'
    | '/docs/components/checkbox'
    | '/docs/components/collapsible'
    | '/docs/components/combobox'
    | '/docs/components/data-table'
    | '/docs/components/date-picker'
    | '/docs/components/dialog'
    | '/docs/components/drawer'
    | '/docs/components/dropdown-menu'
    | '/docs/components/input'
    | '/docs/components/input-otp'
    | '/docs/components/popover'
    | '/docs/components/progress'
    | '/docs/components/radio-group'
    | '/docs/components/select'
    | '/docs/components/sidebar'
    | '/docs/components/skeleton'
    | '/docs/components/slider'
    | '/docs/components/sonner'
    | '/docs/components/spinner'
    | '/docs/components/switch'
    | '/docs/components/tabs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/components'
    | '/docs/installation'
    | '/docs/introduction'
    | '/docs/tailwind-to-kotlin'
    | '/docs/theming'
    | '/docs/components/accordion'
    | '/docs/components/alert'
    | '/docs/components/alert-dialog'
    | '/docs/components/avatar'
    | '/docs/components/badge'
    | '/docs/components/button'
    | '/docs/components/calendar'
    | '/docs/components/card'
    | '/docs/components/carousel'
    | '/docs/components/chart'
    | '/docs/components/checkbox'
    | '/docs/components/collapsible'
    | '/docs/components/combobox'
    | '/docs/components/data-table'
    | '/docs/components/date-picker'
    | '/docs/components/dialog'
    | '/docs/components/drawer'
    | '/docs/components/dropdown-menu'
    | '/docs/components/input'
    | '/docs/components/input-otp'
    | '/docs/components/popover'
    | '/docs/components/progress'
    | '/docs/components/radio-group'
    | '/docs/components/select'
    | '/docs/components/sidebar'
    | '/docs/components/skeleton'
    | '/docs/components/slider'
    | '/docs/components/sonner'
    | '/docs/components/spinner'
    | '/docs/components/switch'
    | '/docs/components/tabs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/theming': {
      id: '/docs/theming'
      path: '/theming'
      fullPath: '/docs/theming'
      preLoaderRoute: typeof DocsThemingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/tailwind-to-kotlin': {
      id: '/docs/tailwind-to-kotlin'
      path: '/tailwind-to-kotlin'
      fullPath: '/docs/tailwind-to-kotlin'
      preLoaderRoute: typeof DocsTailwindToKotlinRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/introduction': {
      id: '/docs/introduction'
      path: '/introduction'
      fullPath: '/docs/introduction'
      preLoaderRoute: typeof DocsIntroductionRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components': {
      id: '/docs/components'
      path: '/components'
      fullPath: '/docs/components'
      preLoaderRoute: typeof DocsComponentsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/tabs': {
      id: '/docs/components/tabs'
      path: '/tabs'
      fullPath: '/docs/components/tabs'
      preLoaderRoute: typeof DocsComponentsTabsRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/switch': {
      id: '/docs/components/switch'
      path: '/switch'
      fullPath: '/docs/components/switch'
      preLoaderRoute: typeof DocsComponentsSwitchRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/spinner': {
      id: '/docs/components/spinner'
      path: '/spinner'
      fullPath: '/docs/components/spinner'
      preLoaderRoute: typeof DocsComponentsSpinnerRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/sonner': {
      id: '/docs/components/sonner'
      path: '/sonner'
      fullPath: '/docs/components/sonner'
      preLoaderRoute: typeof DocsComponentsSonnerRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/slider': {
      id: '/docs/components/slider'
      path: '/slider'
      fullPath: '/docs/components/slider'
      preLoaderRoute: typeof DocsComponentsSliderRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/skeleton': {
      id: '/docs/components/skeleton'
      path: '/skeleton'
      fullPath: '/docs/components/skeleton'
      preLoaderRoute: typeof DocsComponentsSkeletonRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/sidebar': {
      id: '/docs/components/sidebar'
      path: '/sidebar'
      fullPath: '/docs/components/sidebar'
      preLoaderRoute: typeof DocsComponentsSidebarRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/select': {
      id: '/docs/components/select'
      path: '/select'
      fullPath: '/docs/components/select'
      preLoaderRoute: typeof DocsComponentsSelectRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/radio-group': {
      id: '/docs/components/radio-group'
      path: '/radio-group'
      fullPath: '/docs/components/radio-group'
      preLoaderRoute: typeof DocsComponentsRadioGroupRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/progress': {
      id: '/docs/components/progress'
      path: '/progress'
      fullPath: '/docs/components/progress'
      preLoaderRoute: typeof DocsComponentsProgressRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/popover': {
      id: '/docs/components/popover'
      path: '/popover'
      fullPath: '/docs/components/popover'
      preLoaderRoute: typeof DocsComponentsPopoverRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/input-otp': {
      id: '/docs/components/input-otp'
      path: '/input-otp'
      fullPath: '/docs/components/input-otp'
      preLoaderRoute: typeof DocsComponentsInputOtpRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/input': {
      id: '/docs/components/input'
      path: '/input'
      fullPath: '/docs/components/input'
      preLoaderRoute: typeof DocsComponentsInputRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/dropdown-menu': {
      id: '/docs/components/dropdown-menu'
      path: '/dropdown-menu'
      fullPath: '/docs/components/dropdown-menu'
      preLoaderRoute: typeof DocsComponentsDropdownMenuRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/drawer': {
      id: '/docs/components/drawer'
      path: '/drawer'
      fullPath: '/docs/components/drawer'
      preLoaderRoute: typeof DocsComponentsDrawerRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/dialog': {
      id: '/docs/components/dialog'
      path: '/dialog'
      fullPath: '/docs/components/dialog'
      preLoaderRoute: typeof DocsComponentsDialogRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/date-picker': {
      id: '/docs/components/date-picker'
      path: '/date-picker'
      fullPath: '/docs/components/date-picker'
      preLoaderRoute: typeof DocsComponentsDatePickerRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/data-table': {
      id: '/docs/components/data-table'
      path: '/data-table'
      fullPath: '/docs/components/data-table'
      preLoaderRoute: typeof DocsComponentsDataTableRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/combobox': {
      id: '/docs/components/combobox'
      path: '/combobox'
      fullPath: '/docs/components/combobox'
      preLoaderRoute: typeof DocsComponentsComboboxRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/collapsible': {
      id: '/docs/components/collapsible'
      path: '/collapsible'
      fullPath: '/docs/components/collapsible'
      preLoaderRoute: typeof DocsComponentsCollapsibleRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/checkbox': {
      id: '/docs/components/checkbox'
      path: '/checkbox'
      fullPath: '/docs/components/checkbox'
      preLoaderRoute: typeof DocsComponentsCheckboxRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/chart': {
      id: '/docs/components/chart'
      path: '/chart'
      fullPath: '/docs/components/chart'
      preLoaderRoute: typeof DocsComponentsChartRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/carousel': {
      id: '/docs/components/carousel'
      path: '/carousel'
      fullPath: '/docs/components/carousel'
      preLoaderRoute: typeof DocsComponentsCarouselRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/card': {
      id: '/docs/components/card'
      path: '/card'
      fullPath: '/docs/components/card'
      preLoaderRoute: typeof DocsComponentsCardRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/calendar': {
      id: '/docs/components/calendar'
      path: '/calendar'
      fullPath: '/docs/components/calendar'
      preLoaderRoute: typeof DocsComponentsCalendarRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/button': {
      id: '/docs/components/button'
      path: '/button'
      fullPath: '/docs/components/button'
      preLoaderRoute: typeof DocsComponentsButtonRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/badge': {
      id: '/docs/components/badge'
      path: '/badge'
      fullPath: '/docs/components/badge'
      preLoaderRoute: typeof DocsComponentsBadgeRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/avatar': {
      id: '/docs/components/avatar'
      path: '/avatar'
      fullPath: '/docs/components/avatar'
      preLoaderRoute: typeof DocsComponentsAvatarRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/alert-dialog': {
      id: '/docs/components/alert-dialog'
      path: '/alert-dialog'
      fullPath: '/docs/components/alert-dialog'
      preLoaderRoute: typeof DocsComponentsAlertDialogRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/alert': {
      id: '/docs/components/alert'
      path: '/alert'
      fullPath: '/docs/components/alert'
      preLoaderRoute: typeof DocsComponentsAlertRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/accordion': {
      id: '/docs/components/accordion'
      path: '/accordion'
      fullPath: '/docs/components/accordion'
      preLoaderRoute: typeof DocsComponentsAccordionRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
  }
}

interface DocsComponentsRouteChildren {
  DocsComponentsAccordionRoute: typeof DocsComponentsAccordionRoute
  DocsComponentsAlertRoute: typeof DocsComponentsAlertRoute
  DocsComponentsAlertDialogRoute: typeof DocsComponentsAlertDialogRoute
  DocsComponentsAvatarRoute: typeof DocsComponentsAvatarRoute
  DocsComponentsBadgeRoute: typeof DocsComponentsBadgeRoute
  DocsComponentsButtonRoute: typeof DocsComponentsButtonRoute
  DocsComponentsCalendarRoute: typeof DocsComponentsCalendarRoute
  DocsComponentsCardRoute: typeof DocsComponentsCardRoute
  DocsComponentsCarouselRoute: typeof DocsComponentsCarouselRoute
  DocsComponentsChartRoute: typeof DocsComponentsChartRoute
  DocsComponentsCheckboxRoute: typeof DocsComponentsCheckboxRoute
  DocsComponentsCollapsibleRoute: typeof DocsComponentsCollapsibleRoute
  DocsComponentsComboboxRoute: typeof DocsComponentsComboboxRoute
  DocsComponentsDataTableRoute: typeof DocsComponentsDataTableRoute
  DocsComponentsDatePickerRoute: typeof DocsComponentsDatePickerRoute
  DocsComponentsDialogRoute: typeof DocsComponentsDialogRoute
  DocsComponentsDrawerRoute: typeof DocsComponentsDrawerRoute
  DocsComponentsDropdownMenuRoute: typeof DocsComponentsDropdownMenuRoute
  DocsComponentsInputRoute: typeof DocsComponentsInputRoute
  DocsComponentsInputOtpRoute: typeof DocsComponentsInputOtpRoute
  DocsComponentsPopoverRoute: typeof DocsComponentsPopoverRoute
  DocsComponentsProgressRoute: typeof DocsComponentsProgressRoute
  DocsComponentsRadioGroupRoute: typeof DocsComponentsRadioGroupRoute
  DocsComponentsSelectRoute: typeof DocsComponentsSelectRoute
  DocsComponentsSidebarRoute: typeof DocsComponentsSidebarRoute
  DocsComponentsSkeletonRoute: typeof DocsComponentsSkeletonRoute
  DocsComponentsSliderRoute: typeof DocsComponentsSliderRoute
  DocsComponentsSonnerRoute: typeof DocsComponentsSonnerRoute
  DocsComponentsSpinnerRoute: typeof DocsComponentsSpinnerRoute
  DocsComponentsSwitchRoute: typeof DocsComponentsSwitchRoute
  DocsComponentsTabsRoute: typeof DocsComponentsTabsRoute
}

const DocsComponentsRouteChildren: DocsComponentsRouteChildren = {
  DocsComponentsAccordionRoute: DocsComponentsAccordionRoute,
  DocsComponentsAlertRoute: DocsComponentsAlertRoute,
  DocsComponentsAlertDialogRoute: DocsComponentsAlertDialogRoute,
  DocsComponentsAvatarRoute: DocsComponentsAvatarRoute,
  DocsComponentsBadgeRoute: DocsComponentsBadgeRoute,
  DocsComponentsButtonRoute: DocsComponentsButtonRoute,
  DocsComponentsCalendarRoute: DocsComponentsCalendarRoute,
  DocsComponentsCardRoute: DocsComponentsCardRoute,
  DocsComponentsCarouselRoute: DocsComponentsCarouselRoute,
  DocsComponentsChartRoute: DocsComponentsChartRoute,
  DocsComponentsCheckboxRoute: DocsComponentsCheckboxRoute,
  DocsComponentsCollapsibleRoute: DocsComponentsCollapsibleRoute,
  DocsComponentsComboboxRoute: DocsComponentsComboboxRoute,
  DocsComponentsDataTableRoute: DocsComponentsDataTableRoute,
  DocsComponentsDatePickerRoute: DocsComponentsDatePickerRoute,
  DocsComponentsDialogRoute: DocsComponentsDialogRoute,
  DocsComponentsDrawerRoute: DocsComponentsDrawerRoute,
  DocsComponentsDropdownMenuRoute: DocsComponentsDropdownMenuRoute,
  DocsComponentsInputRoute: DocsComponentsInputRoute,
  DocsComponentsInputOtpRoute: DocsComponentsInputOtpRoute,
  DocsComponentsPopoverRoute: DocsComponentsPopoverRoute,
  DocsComponentsProgressRoute: DocsComponentsProgressRoute,
  DocsComponentsRadioGroupRoute: DocsComponentsRadioGroupRoute,
  DocsComponentsSelectRoute: DocsComponentsSelectRoute,
  DocsComponentsSidebarRoute: DocsComponentsSidebarRoute,
  DocsComponentsSkeletonRoute: DocsComponentsSkeletonRoute,
  DocsComponentsSliderRoute: DocsComponentsSliderRoute,
  DocsComponentsSonnerRoute: DocsComponentsSonnerRoute,
  DocsComponentsSpinnerRoute: DocsComponentsSpinnerRoute,
  DocsComponentsSwitchRoute: DocsComponentsSwitchRoute,
  DocsComponentsTabsRoute: DocsComponentsTabsRoute,
}

const DocsComponentsRouteWithChildren = DocsComponentsRoute._addFileChildren(
  DocsComponentsRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsComponentsRoute: typeof DocsComponentsRouteWithChildren
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsIntroductionRoute: typeof DocsIntroductionRoute
  DocsTailwindToKotlinRoute: typeof DocsTailwindToKotlinRoute
  DocsThemingRoute: typeof DocsThemingRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsComponentsRoute: DocsComponentsRouteWithChildren,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsIntroductionRoute: DocsIntroductionRoute,
  DocsTailwindToKotlinRoute: DocsTailwindToKotlinRoute,
  DocsThemingRoute: DocsThemingRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
